In [2]:
import torch

In [3]:
print(torch.__version__)

2.9.1+cpu


In [10]:
##CRreating a tensor

x=torch.empty(2,3)
x

tensor([[1.8617e-12, 1.9030e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [ ]:
type(x)


torch.Tensor

In [14]:
torch.zeros(5,3),torch.ones(2,4)

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [19]:
torch.manual_seed(42)
torch.rand(2,3)


tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [20]:
torch.tensor([[12,12,13],[12,34,42]])

tensor([[12, 12, 13],
        [12, 34, 42]])

In [24]:
torch.arange(0,10),torch.linspace(0,1,5),torch.eye(3),torch.full((2,3),5)

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000]),
 tensor([[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]),
 tensor([[5, 5, 5],
         [5, 5, 5]]))

#### Tensor shapes

In [29]:
x=torch.tensor([[1,2,3],[4,5,6]])

In [30]:
x.shape

torch.Size([2, 3])

In [31]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [32]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [33]:
torch.rand(x.shape)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [35]:
x,x.dtype

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.int64)

In [36]:
x+2,x-2,x*2,x/2

(tensor([[3, 4, 5],
         [6, 7, 8]]),
 tensor([[-1,  0,  1],
         [ 2,  3,  4]]),
 tensor([[ 2,  4,  6],
         [ 8, 10, 12]]),
 tensor([[0.5000, 1.0000, 1.5000],
         [2.0000, 2.5000, 3.0000]]))

In [37]:
a=torch.rand(2,3)
b=torch.rand(2,3)
a,b

(tensor([[0.8694, 0.5677, 0.7411],
         [0.4294, 0.8854, 0.5739]]),
 tensor([[0.2666, 0.6274, 0.2696],
         [0.4414, 0.2969, 0.8317]]))

In [48]:
y=a-b
a+b,a**b,a/b,a%b,y,a**b
c=a/b

In [41]:
torch.abs(y)

tensor([[0.6028, 0.0597, 0.4715],
        [0.0120, 0.5885, 0.2578]])

In [45]:
torch.round(y),torch.ceil(y),torch.floor(y)

(tensor([[1., -0., 0.],
         [-0., 1., -0.]]),
 tensor([[1., -0., 1.],
         [-0., 1., -0.]]),
 tensor([[ 0., -1.,  0.],
         [-1.,  0., -1.]]))

In [52]:
torch.clamp(c,min=1.0,max=3.0)

tensor([[3.0000, 1.0000, 2.7485],
        [1.0000, 2.9821, 1.0000]])

In [64]:
d=torch.randint(size=(2,3),low=0,high=10)
d

tensor([[9, 6, 2],
        [0, 6, 2]])

In [58]:
torch.sum(d),torch.mean(d.float()),torch.max(d),torch.min(d),torch.sum(d,dim=0),torch.sum(d,dim=1)

(tensor(23),
 tensor(3.8333),
 tensor(9),
 tensor(0),
 tensor([11,  3,  9]),
 tensor([ 7, 16]))

In [59]:
torch.mean(d.float(),dim=1),torch.max(d,dim=0),torch.min(d,dim=1)

(tensor([2.3333, 5.3333]),
 torch.return_types.max(
 values=tensor([9, 3, 5]),
 indices=tensor([1, 1, 0])),
 torch.return_types.min(
 values=tensor([0, 3]),
 indices=tensor([1, 1])))

In [62]:
torch.std(d.float())

tensor(3.0605)

In [66]:
torch.argmax(d),torch.argmin(d)

(tensor(0), tensor(3))

#### Matrix multiplication

In [69]:
a=torch.randint(size=(2,3),low=0,high=10)
b=torch.randint(size=(3,2),low=0,high=10)

a,b

(tensor([[3, 0, 1],
         [1, 7, 9]]),
 tensor([[4, 3],
         [8, 9],
         [3, 7]]))

In [70]:
torch.matmul(a,b),a.matmul(b),a@b

(tensor([[ 15,  16],
         [ 87, 129]]),
 tensor([[ 15,  16],
         [ 87, 129]]),
 tensor([[ 15,  16],
         [ 87, 129]]))

In [71]:
torch.cuda.is_available()

False

In [72]:
device=torch.device("cuda" if torch.cuda.is_available() else "cpu")